### ISSUE TITLE
Invalid TOML output when combining #[serde(untagged)] with Vec<(_)>

### ISSUE THREAD

**Issue by jonhoo** [alexcrichton/toml-rs#449]
The following code:
```rust
use serde_derive::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Serialize, Deserialize)]
#[serde(untagged)]
enum Foo {
    Value(i32),
    Table { value: i32 },
}

fn main() {
    let output = toml::to_string_pretty(&HashMap::from([(
        "test",
        vec![("one", Foo::Value(1)), ("two", Foo::Table { value: 2 })],
    )]))
    .unwrap();

    println!("{}", output);

    let _: Vec<(String, Foo)> = toml::from_str(&output).unwrap();
}

```

produces the following invalid TOML document ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a1235f66680fc9148aa5ef815a2a5077)):
```toml
test = [
    [
    'one',
    1,
],
    [
    'two'
[[test]]
value = 2
,
],
]
```
it also (correctly) fails to parse said output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Wanted { expected: "a right bracket", found: "a left bracket" }, line: Some(7), col: 0, at: Some(52), message: "", key: [] } }', src/main.rs:24:57
```

**Comment by SteadBytes** [comment]
I've also run into this :+1:  Interestingly, it seems to _deserializes_ correctly but fails to correctly round trip; producing incorrect serialized output as in @jonhoo's example:

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=467cd57df8e821d52f7f3cf58534a6d7)
```rust
use serde::{Deserialize, Serialize};
use toml;

#[derive(Serialize, Deserialize, Debug)]
struct Config {
    actions: Vec<Action>,
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
enum Action {
    Exec { name: Option<String>, run: String },
    Builtin(BuiltinAction),
}

#[derive(Serialize, Deserialize, Debug)]
enum BuiltinAction {
    CreateTag,
}

fn main() {
    let raw = r#"
        actions = [
           "CreateTag",
           { name="test", run="make test"},
        ]"#;

    // Deserialize - OK
    let conf: Config = toml::from_str(raw).unwrap();
    println!("conf:\n{:?}\n", conf);

    // Serialize - no error, but invalid output
    let raw = toml::to_string(&conf).unwrap();
    println!("raw:\n{}", raw);

    // Deserialize again - error
    let conf: Config = toml::from_str(&raw).unwrap();
    println!("conf:\n{:?}\n", conf);
}
```

```
conf: Config { actions: [Builtin(CreateTag), Exec { name: Some("test"), run: "make test" }] }

serialized:
actions = ["CreateTag"
[[actions]]
name = "test"
run = "make test"
]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Wanted { expected: "a right bracket", found: "a left bracket" }, line: Some(1), col: 0, at: Some(23), message: "", key: [] } }', src/main.rs:37:52
```

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
